version: '3'
services:
  go-app:
    build:
      context: ./go-app # Path to your Go application's Dockerfile
    ports:
      - "8000:8000" # Expose your Go application's port
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=KM5

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: KM5
